export const nekoEffects = [
  { id: "transit-spine", label: "Transit Spine", code: "TRS", category: "city", mode: "lines", source: "Reactive Lines", description: "Responsive routes carrying traffic and signal pressure." },
  { id: "district-grid", label: "District Grid", code: "DSG", category: "city", mode: "grid", source: "Interactive Grid", description: "Live city sectors, studios, clubs and patrol nodes." },
  { id: "patrol-coordinates", label: "Patrol Coordinates", code: "PCR", category: "security", mode: "cursor", source: "Axis Cursor", description: "Full-field location and target acquisition instrument." },
  { id: "crew-orbit", label: "Crew Orbit", code: "CRO", category: "city", mode: "orbit", source: "Proximity Orbit", description: "Crew, releases and districts arranged by proximity." },
  { id: "signal-board", label: "Signal Board", code: "SGB", category: "broadcast", mode: "led", source: "Pixel LED Display", description: "Neko City transit, club and emergency broadcasts." },
  { id: "window-telemetry", label: "Window Telemetry", code: "WTL", category: "city", mode: "grid", source: "Blinking Squares", description: "Illuminated district activity and network presence." },
  { id: "courier-route", label: "Courier Route", code: "DCR", category: "city", mode: "route", source: "Snake Grid", description: "A packet courier navigating damaged city sectors." },
  { id: "infrastructure-void", label: "Infrastructure Void", code: "IFV", category: "city", mode: "void", source: "Grid Hole", description: "A collapsed archive sector or forbidden location." },
  { id: "security-perimeter", label: "Security Perimeter", code: "SCP", category: "security", mode: "border", source: "Electric Border", description: "Electrified boundary for restricted systems." },
  { id: "access-handshake", label: "Access Handshake", code: "AHS", category: "security", mode: "text", source: "Encrypt Button", description: "Authentication language resolving from encrypted noise." },
  { id: "scanner-emission", label: "Scanner Emission", code: "SCN", category: "security", mode: "arcs", source: "Wave Arcs", description: "Radar, sonar and patrol propagation scan." },
  { id: "system-heartbeat", label: "System Heartbeat", code: "SHB", category: "signal", mode: "pulse", source: "Pulse Lines", description: "Rhythmic impulses travelling between modules." },
  { id: "control-surface", label: "Control Surface", code: "CTL", category: "security", mode: "grid", source: "Reactive Grid", description: "Tactile sectors responding to local input." },
  { id: "magnetic-field", label: "Magnetic Field", code: "MGF", category: "signal", mode: "field", source: "Kinetic Grid", description: "Markers aligning around an invisible force." },
  { id: "signal-density", label: "Signal Density", code: "SDN", category: "signal", mode: "dots", source: "Dot Matrix", description: "Spectral population and sound-cluster field." },
  { id: "broadcast-field", label: "Broadcast Field", code: "BRF", category: "signal", mode: "lines", source: "Line Ripple Background", description: "Radio and sound transmissions bending the grid." },
  { id: "frequency-bleed", label: "Frequency Bleed", code: "FQB", category: "signal", mode: "waves", source: "Chromatic Waves", description: "Separated damaged frequency channels." },
  { id: "night-rail", label: "Night Rail", code: "NTR", category: "city", mode: "tunnel", source: "Particle Tunnel", description: "High-speed movement between Neko City districts." },
  { id: "spectral-fabric", label: "Spectral Fabric", code: "SPF", category: "signal", mode: "lines", source: "Reactive Lines", description: "A responsive membrane for audio and pressure." },
  { id: "signal-residue", label: "Signal Residue", code: "SGR", category: "signal", mode: "trail", source: "Fluid Trail", description: "Damaged phosphor traces left by live input." },
  { id: "packet-decay", label: "Packet Decay", code: "PKD", category: "signal", mode: "particles", source: "Pixel Drift", description: "Component pixels detaching as integrity drops." },
  { id: "city-core", label: "City Intelligence Core", code: "CIC", category: "city", mode: "orb", source: "Cosmic Orb", description: "Contained intelligence representing a city system." },
  { id: "archive-materialize", label: "Archive Materialize", code: "ARM", category: "archive", mode: "reveal", source: "Pixel Reveal", description: "Images recovering from deterministic pixels." },
  { id: "memory-assembly", label: "Memory Assembly", code: "MAS", category: "archive", mode: "tiles", source: "Pixel Unfold", description: "Archive fragments assembling into a memory." },
  { id: "surveillance-decode", label: "Surveillance Decode", code: "SVD", category: "archive", mode: "dots", source: "Dot Image Reveal", description: "Evidence reconstructed from scanning points." },
  { id: "terminal-recovery", label: "Terminal Recovery", code: "TMR", category: "archive", mode: "ascii", source: "ASCII Reveal", description: "Image memory recovered through terminal glyphs." },
  { id: "corrupted-hologram", label: "Corrupted Hologram", code: "CHG", category: "archive", mode: "liquid", source: "Liquid Distortion", description: "A damaged image surface slipping out of phase." },
  { id: "signal-impact", label: "Signal Impact", code: "SGI", category: "archive", mode: "ripple", source: "Image Ripple", description: "Concentric disruption through an evidence frame." },
  { id: "identity-mask", label: "Identity Mask", code: "IDM", category: "archive", mode: "pixel", source: "Pixelate Image", description: "Privacy and identity suppression field." },
  { id: "patrol-searchlight", label: "Patrol Searchlight", code: "PSL", category: "security", mode: "spotlight", source: "Image Spotlight", description: "A controlled beam revealing hidden evidence." },
  { id: "damaged-signage", label: "Damaged Signage", code: "DMS", category: "type", mode: "text", source: "Glitch Text", description: "Broken street labels and pirate transmissions." },
  { id: "terminal-decode", label: "Terminal Decode", code: "TDC", category: "type", mode: "text", source: "Scramble Text", description: "Operational text resolving from system noise." },
  { id: "intercepted-message", label: "Intercepted Message", code: "ICM", category: "type", mode: "text", source: "Random Letter Swap", description: "Unstable translated communication." },
  { id: "neon-failure", label: "Neon Failure", code: "NEF", category: "type", mode: "text", source: "Flicker Text", description: "Aging signs and failing equipment labels." },
  { id: "perimeter-type", label: "Perimeter Type", code: "PRT", category: "type", mode: "orbit-text", source: "Text Path", description: "Circular warnings and device inscriptions." },
  { id: "character-broadcast", label: "Character Broadcast", code: "CBR", category: "type", mode: "type-wave", source: "Character Waves", description: "Music-reactive language transmission." },
  { id: "ascii-overload", label: "ASCII Overload", code: "AOV", category: "type", mode: "ascii", source: "ASCII Flame", description: "Generator heat and digital combustion." },
] as const;

export type NekoEffectId = (typeof nekoEffects)[number]["id"];
export type EffectMode = (typeof nekoEffects)[number]["mode"];
export type EffectCategory = (typeof nekoEffects)[number]["category"];
